/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProvasRouteImport } from './routes/provas'
import { Route as InfluencersRouteImport } from './routes/influencers'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampanhasIdRouteImport } from './routes/campanhas.$id'
import { Route as ApiSeedRouteImport } from './routes/api.seed'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvasRoute = ProvasRouteImport.update({
  id: '/provas',
  path: '/provas',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersRoute = InfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasIdRoute = CampanhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampanhasRoute,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/influencers': typeof InfluencersRoute
  '/provas': typeof ProvasRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/seed': typeof ApiSeedRoute
  '/campanhas/$id': typeof CampanhasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/influencers': typeof InfluencersRoute
  '/provas': typeof ProvasRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/seed': typeof ApiSeedRoute
  '/campanhas/$id': typeof CampanhasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campanhas': typeof CampanhasRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/influencers': typeof InfluencersRoute
  '/provas': typeof ProvasRoute
  '/relatorios': typeof RelatoriosRoute
  '/api/seed': typeof ApiSeedRoute
  '/campanhas/$id': typeof CampanhasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campanhas'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/influencers'
    | '/provas'
    | '/relatorios'
    | '/api/seed'
    | '/campanhas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campanhas'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/influencers'
    | '/provas'
    | '/relatorios'
    | '/api/seed'
    | '/campanhas/$id'
  id:
    | '__root__'
    | '/'
    | '/campanhas'
    | '/clientes'
    | '/configuracoes'
    | '/financeiro'
    | '/influencers'
    | '/provas'
    | '/relatorios'
    | '/api/seed'
    | '/campanhas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampanhasRoute: typeof CampanhasRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InfluencersRoute: typeof InfluencersRoute
  ProvasRoute: typeof ProvasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ApiSeedRoute: typeof ApiSeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provas': {
      id: '/provas'
      path: '/provas'
      fullPath: '/provas'
      preLoaderRoute: typeof ProvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers': {
      id: '/influencers'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof InfluencersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/$id': {
      id: '/campanhas/$id'
      path: '/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof CampanhasIdRouteImport
      parentRoute: typeof CampanhasRoute
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampanhasRouteChildren {
  CampanhasIdRoute: typeof CampanhasIdRoute
}

const CampanhasRouteChildren: CampanhasRouteChildren = {
  CampanhasIdRoute: CampanhasIdRoute,
}

const CampanhasRouteWithChildren = CampanhasRoute._addFileChildren(
  CampanhasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampanhasRoute: CampanhasRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  InfluencersRoute: InfluencersRoute,
  ProvasRoute: ProvasRoute,
  RelatoriosRoute: RelatoriosRoute,
  ApiSeedRoute: ApiSeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
