// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irewbhcnazteojoirsyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZXdiaGNuYXp0ZW9qb2lyc3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE2NDI0MzgsImV4cCI6MjA5NzIxODQzOH0.gD4Op18U2rqW624cHo4pEpYxV4LY9tg6Vg3LzvBfiWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});